# Generated by Django 2.2.5 on 2019-09-28 01:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='after',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AddField(
            model_name='log',
            name='before',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
