# Generated by Django 2.2.5 on 2019-09-28 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190928_0438'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='description',
            field=models.CharField(default='', max_length=380),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='action',
            name='users',
            field=models.ManyToManyField(related_name='actions', through='user.UserAction', to='user.User'),
        ),
    ]
