# Generated by Django 2.2.5 on 2019-09-28 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20190929_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vk_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
